
	git rm 64B.S
	git rm 64B.o
	git rm a.d
	git rm bk.S
	git rm bk64B.S
	git rm core.4178
	git rm core_functions.S
	git rm core_functions.S.bak
	git rm core_functions.c
	git rm core_functions.o
	git rm core_functions.s
	git rm core_functions.s.610
	git rm core_functions.s.611
	git rm core_functions.s.611.1
	git rm core_functions.s.unchecked
	git rm core_functions64.S
	git rm example
	git rm example_new
	git rm fjr.S
	git rm fjr.c
	git rm fjr.s
	git rm haha
	git rm log/run.log.v2.1
	git rm ppl.S
	git rm run.log
	git rm sqlnet.log
	git rm test.o
	git rm x.c
	git rm xq.c
	git rm xq.s

